name: Create Release with Extension

on:
  push:
    tags:
      - 'v*'  # Trigger on any version tag (e.g., v1.0.0, v1.2.3)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip extension folder
        run: |
          cd my-extension
          zip -r ../friendsbook-${{ github.ref_name }}.zip .

      - name: Create Release and Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Chrome Extension Bundle"
          files: |
            friendsbook-${{ github.ref_name }}.zip